### ISSUE TITLE
Example of use

### ISSUE THREAD

**Issue by pajaro5** [telkins/laravel-dag-manager#3]
Hi Travis 
Thanks for this amazing package.   I'd like to know if there are some usage examples, that shows how to get specific levels.  I'm looking to build a Dag like this: 

![image](https://user-images.githubusercontent.com/5140280/47407694-f63ebf00-d721-11e8-913e-7ea91648958e.png)
Image from https://stackoverflow.com/questions/18299842/how-to-develop-a-database-schema-for-a-tree-structuredirected-acyclic-graph/18434333#18434333

In my case,  I need to represent a sillabus tree (dag),  where each node represents an assigment for each level.

In review the tests, but I cant find something that gets nodes by level or by fathers.

Thanks again.

Pablo Robayo

**Comment by telkins** [comment]
@pajaro5 

I'm happy to hear that this package is useful/helpful for you.

First, I'd like to talk about a quick concern about the "vertical relations" that you have in your diagram.  I'm afraid I don't quite follow how these are intended to behave with regards to a DAG.  If it's simply to show that each node in the "vertical relation" is a sibling, then it makes sense.  If it's something else, then it may not be supported.

Now, in order to retrieve nodes "by fathers", I believe you should be able to use `MyModel::dagDescendantsOf()` where `MyModel` is an Eloquent model that uses the `Telkins\Models\Traits\IsDagManaged` trait.  You specify the ID of the "father" along with the "source" and then you can call `get()` to get them all.  This will return **all** descendants...not just the direct descendants.  You can then use the model's `hops` attribute to find those that are direct descendants or find those at the "level" in which you are interested.

Hmmm....looks like I just found an error/issue with the trait related to `fillable` and `casts`.  I will have to take a look at that ASAP.  :-)

Now, I'm not sure if this helps you or not.  I hope so, but please respond and let me know how it goes and what, if anything, you'd like to see going forward.

Thanks,

Travis

**Comment by telkins** [comment]
> Hmmm....looks like I just found an error/issue with the trait related to fillable and casts. I will have to take a look at that ASAP. :-)

False alarm...!  Whew...!  Looks like I was looking at the wrong file.  :-)

**Comment by pajaro5** [comment]
Hi Travis

So, about the vertical relations, they are required because I'm building a curriculum system, so there are some graphs that are concurrent (vertical) and others that act as prerequisites (horizontal, fathers)

Here is an example:
![image](https://user-images.githubusercontent.com/5140280/47441579-113b1e80-d776-11e8-96e1-d68666a20706.png)

Image taken from https://goo.gl/images/M3JNem

Before I find your package, I was thinking about a recursive many to many relationship.  Does it makes sense to you?

Greetings from Quito

Pablo

**Comment by telkins** [comment]
@pajaro5 

Hi again.  Sorry I never replied.  To be honest, I'm not sure if I saw that there was another post here.

Anyway, you may know by now if this package helped you or not.  I would like to hear whether or not it's been helpful.

Whatever the case, it *looks* like it will work, but I'm not completely understanding the graph you posted.  It does *not* appear that anything "cycles", in which case, it should work.  If there's a "cycle", however, then it will not work.  (This is one of the "rules" of a directed *acyclic* graph...in that it cannot "cycle" back.)

I'm going to close this, but please feel free to respond and/or re-open if you think it's necessary.

Take care,

Travis
